export type VoteErrorCode =
  | "TOKEN_INVALID"
  | "TOKEN_ALREADY_USED"
  | "TOKEN_LOCKED"
  | "ELECTION_NOT_FOUND"
  | "ELECTION_NOT_STARTED"
  | "ELECTION_ENDED"
  | "ALREADY_VOTED"
  | "CANDIDATE_NOT_FOUND"
  | "NO_VOTE_SESSION"
  | "RATE_LIMITED"
  | "VOTER_NOT_ELIGIBLE"
  | "INVALID_INPUT"
  | "EMAIL_SEND_FAILED";
